<template>
    <v-row>
        <v-col
            md="4"
        >
            <v-card
                min-height="100px"
            >
                <v-sheet
                    width="80px"
                    style="position:absolute;top:-15px;right:10px"
                    height="80px"
                    elevation="10"
                    color="error"
                >
                    <v-row
                        class="fill-height"
                        align="center"
                        justify="center"
                    >
                        <v-icon
                            x-large
                            dark
                        >mdi-car</v-icon>
                    </v-row>
                </v-sheet>
                <v-card-title>10</v-card-title>
                <v-card-subtitle>Mobil</v-card-subtitle>
                <v-card-actions>
                    <v-btn
                        text
                        small
                        color="primary"
                    >
                        Selengkapnya
                    </v-btn>
                </v-card-actions>
            </v-card>
        </v-col>
        <v-col
            md="4"
        >
            <v-card
                min-height="100px"
            >
                <v-sheet
                    width="80px"
                    style="position:absolute;top:-15px;right:10px"
                    height="80px"
                    elevation="10"
                    color="primary"
                >
                    <v-row
                        class="fill-height"
                        align="center"
                        justify="center"
                    >
                        <v-icon
                            x-large
                            dark
                        >mdi-account</v-icon>
                    </v-row>
                </v-sheet>
                <v-card-title>5</v-card-title>
                <v-card-subtitle>Data Admin</v-card-subtitle>
                <v-card-actions>
                    <v-btn
                        text
                        small
                        color="primary"
                    >
                        Selengkapnya
                    </v-btn>
                </v-card-actions>
            </v-card>
        </v-col>
        <v-col
            md="4"
        >
            <v-card
                min-height="100px"
            >
                <v-sheet
                    width="80px"
                    style="position:absolute;top:-15px;right:10px"
                    height="80px"
                    elevation="10"
                    color="success"
                >
                    <v-row
                        class="fill-height"
                        align="center"
                        justify="center"
                    >
                        <v-icon
                            x-large
                            dark
                        >mdi-currency-usd</v-icon>
                    </v-row>
                </v-sheet>
                <v-card-title>2</v-card-title>
                <v-card-subtitle>Pemesanan Masuk</v-card-subtitle>
                <v-card-actions>
                    <v-btn
                        text
                        small
                        color="primary"
                    >
                        Selengkapnya
                    </v-btn>
                </v-card-actions>
            </v-card>
        </v-col>
    </v-row>
</template>